# Generated by Django 3.2 on 2021-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmSupply', '0002_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
